### ISSUE TITLE
How to access the LOH, TAI, LST information for CCLE cell lines?

### ISSUE THREAD

**Issue by haoecust** [shirotak/pancancer_hrd_analysis#2]
Hi Shirotak,

How can we access the LOH, TAI, LST information of CCLE cell lines generated in your paper? Since CCLE is the largest comprehensive cancer cell lines database, the HRDscore feature calculated by your wonderful work would be very helpful on cancer cell related studies.

Best

Hao

**Comment by shirotak** [comment]
Hi Hao

It is calculated using scarHRD by combining already published data. 
Please refer to the method section of the paper.

Shiro

**Comment by haoecust** [comment]
> Hi Hao
> 
> It is calculated using scarHRD by combining already published data.
> Please refer to the method section of the paper.
> 
> Shiro

Thank your very much, Shiro.  It could be calculated from the COSMIC processing data.  Do you mind to upload or share your CCLE cell line HRD infor. results table. That may be very useful for paper citations. 

Best

Hao

**Comment by shirotak** [comment]
Please refer to "Data_for_6AB.tsv" in "data" directory.

Best,
Shiro
